name: stable
on:
    push:
        branches:
            - stable
jobs:
    stable:
        name: Build and publish the stable channel
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
            - name: Setup Toltec dependencies
              uses: ./.github/actions/setup
            - name: Build packages
              run: make repo FLAGS='--remote-repo ${{ secrets.REMOTE_HTTP }}/stable'
            - name: Sync packages with the remote repository
              uses: ./.github/actions/sync-repository
              with:
                local-path: build/repo/
                ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
                ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
                remote-path: ${{ secrets.REMOTE_SSH }}:/srv/toltec/stable
            - name: Send notification to Discord
              continue-on-error: true
              uses: ./.github/actions/discord-send
              with:
                channel: ${{ secrets.DISCORD_STABLE_CHANNEL_ID }}
                token: ${{ secrets.DISCORD_STABLE_CHANNEL_TOKEN }}
                title: New Toltec stable update available
                link: https://toltec-dev.org/stable
                color: 0x2ea043
                message: ${{ github.event.head_commit.message }}
